[package]
name = "floresta-cli"
version = "0.1.0"
edition = "2021"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
license = "MIT"

[dependencies]
jsonrpc = "0.14.1"
clap = { version = "4.0.29", features = ["derive"] }
bitcoin = { version = "0.29", features = ["serde", "std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "*"
