[workspace]
members = [
    "floresta",
    "floresta-chain",
    "floresta-cli",
    "floresta-common",
    "floresta-electrum",
    "floresta-watch-only",
    "floresta-wire",
]

[patch."https://github.com/rust-lang/crates.io-index"]
bitcoin = { git = "https://github.com/Davidson-Souza/rust-bitcoin", rev = "a320c6535567acd3771da37759a7644eea5c6eb2" }
