[package]
name = "floresta-watch-only"
version = "0.1.0"
edition = "2021"
description = "A simple, lightweight and Electrum-First, watch-only wallet"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
keywords = ["bitcoin", "watch-only", "electrum-server"]
license = "MIT"

[dependencies]
serde = "1.0.0"
serde_json = { version = "1.0.0", features = ["alloc"] }
anyhow = "1.0.70"
bitcoin = { version = "0.29.2", features = ["serde"] }
kv = "0.24.0"
log = "0.4"
thiserror = "1.0"
floresta-common = { path = "../floresta-common" }

[dev-dependencies]
rand = "0.8.5"
