[package]
name = "floresta"
version = "0.1.0"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
edition = "2021"
description = """
    A modular and extensible framework for building Utreexo based Bitcoin nodes.
"""
repository = "https://github.com/Davidson-Souza/Floresta"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "utreexo", "node", "blockchain", "rust"]
categories = ["bitcoin", "blockchain", "node"]

[dependencies]
floresta-common = { path = "../floresta-common" }
floresta-chain = { path = "../floresta-chain" }
floresta-wire = { path = "../floresta-wire" }
floresta-watch-only = { path = "../floresta-watch-only" }
rustreexo = { git = "https://www.github.com/mit-dci/rustreexo" }

[dev-dependencies]
async-std = "1.12.0"
bitcoin = { version = "0.29", features = [
    "serde",
    "no-std",
    "bitcoinconsensus",
] }

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "node"
path = "examples/node.rs"

[[example]]
name = "watch-only"
path = "examples/watch-only.rs"

[[example]]
name = "chainstate-builder"
path = "examples/chainstate-builder.rs"
