[package]
name = "floresta"
version = "0.1.0"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
edition = "2021"
description = """
    A modular and extensible framework for building Utreexo based Bitcoin nodes.
"""
repository = "https://github.com/Davidson-Souza/Floresta"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "utreexo", "node", "blockchain", "rust"]
categories = ["bitcoin", "blockchain", "node"]

[dependencies]
floresta-common = { path = "../floresta-common" }
floresta-chain = { path = "../floresta-chain" }
floresta-wire = { path = "../floresta-wire" }
floresta-watch-only = { path = "../floresta-watch-only", features = [
    "memory-database",
], optional = true }
floresta-electrum = { path = "../floresta-electrum", optional = true }

[dev-dependencies]
rustreexo = "0.1.0"
miniscript = "10.0.0"
async-std = "1.12.0"
bitcoin = { version = "0.29", features = [
    "serde",
    "no-std",
    "bitcoinconsensus",
] }

floresta = { version = "0.1.0", path = "../floresta", features = [
    "bitcoinconsensus",
    "memory-database",
    "electrum-server",
    "watch-only-wallet",
] }

[features]
default = ["bitcoinconsensus", "electrum-server", "watch-only-wallet"]
bitcoinconsensus = ["floresta-chain/bitcoinconsensus"]
memory-database = ["floresta-watch-only/memory-database"]
electrum-server = ["floresta-electrum"]
watch-only-wallet = ["floresta-watch-only"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[[example]]
name = "node"
path = "examples/node.rs"

[[example]]
name = "watch-only"
path = "examples/watch-only.rs"

[[example]]
name = "chainstate-builder"
path = "examples/chainstate-builder.rs"
