[package]
name = "floresta-electrum"
version = "0.1.0"
edition = "2021"

[dependencies]
floresta-common = { path = "../floresta-common" }
floresta-chain = { path = "../floresta-chain" }
floresta-watch-only = { path = "../floresta-watch-only" }

rustreexo = "0.1.0"
btcd-rpc = { git = "https://github.com/Davidson-Souza/rust-btcd-rpc", features = [
    "utreexod",
], branch = "use-reqwest", optional = true }
sha2 = "^0.10.6"
async-std = { version = "1.12.0", features = ["attributes"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kv = "0.24.0"
miniscript = { git = "https://github.com/douglaz/rust-miniscript.git", branch = "master-2023-03-30" }
futures = "0.3.4"
rmp-serde = { optional = true, version = "1.1.1" }
toml = "0.5.10"
bitcoin = { version = "0.29", features = ["serde", "std", "bitcoinconsensus"] }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1"
rand = "0.8.5"
