[package]
name = "floresta-wire"
version = "0.1.0"
edition = "2021"

[dependencies]
rustreexo = "0.1.0"
btcd-rpc = { git = "https://github.com/Davidson-Souza/rust-btcd-rpc", features = [
    "utreexod",
], branch = "use-reqwest", optional = true }
sha2 = "^0.10.6"
async-std = { version = "1.12.0", features = ["attributes", "alloc"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kv = "0.24.0"
futures = "0.3.4"
rmp-serde = { optional = true, version = "1.1.1" }
toml = "0.5.10"
rand = "0.8.5"
bitcoin = { version = "0.29", features = ["serde", "std", "bitcoinconsensus"] }
dns-lookup = "1.0.8"
ctrlc = "3.2.5"
floresta-chain = { path = "../floresta-chain" }
thiserror = "1.0"
floresta-common = { path = "../floresta-common" }
oneshot = "0.1.5"

[dev-dependencies]
pretty_assertions = "1"

[features]
default = []
pruned_utreexo_chainstate = []