name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # try to build
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # run all tests
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  linting:

    runs-on: ubuntu-latest

    steps:
    # cargo fmt
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --all --check

    # run cargo clippy
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --all

  cross-testing:
    strategy:
      matrix:
        rust: [stable, nightly, 1.64]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cross compile
        run: cargo test --verbose
